# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Live Streaming App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Live Streaming App
# Add the Firebase pod for Google Analytics
pod 'FirebaseAnalytics'

# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'GoogleSignIn'
pod 'Alamofire'
pod 'HaishinKit'
#pod 'MobileVLCKit'

  target 'Live Streaming AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Live Streaming AppUITests' do
    # Pods for testing
  end

end
